CREATE DATABASE IF NOT EXISTS bdWawakusi;
USE bdWawakusi;

-- =========================
-- ROLES
-- =========================
CREATE TABLE ROL (
    IDROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

-- =========================
-- PERMISOS
-- =========================
CREATE TABLE PERMISO (
    IDPERMISO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255)
);

-- =========================
-- ROL - PERMISO
-- =========================
CREATE TABLE ROL_PERMISO (
    IDROL_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ROL_ID INT NOT NULL,
    PERMISO_ID INT NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(IDROL),
    FOREIGN KEY (PERMISO_ID) REFERENCES PERMISO(IDPERMISO)
);

-- =========================
-- USUARIOS
-- =========================
CREATE TABLE USUARIO (
    IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(255) NOT NULL,
    PASSWORD TINYBLOB NOT NULL,
    ROL_ID INT,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(IDROL)
);

-- =========================
-- CLIENTES
-- =========================
CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(255),
    DIRECCION VARCHAR(255),
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

-- =========================
-- CATEGORÍAS
-- =========================
CREATE TABLE CATEGORIA (
    CODCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL
);

-- =========================
-- PRODUCTOS
-- =========================
CREATE TABLE PRODUCTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    MARCA VARCHAR(100),
    DESCRIPCION TEXT,
    COSTO FLOAT NOT NULL,
    PRECIO_MIN DECIMAL(10,2) NOT NULL,
    PRECIO_MAX DECIMAL(10,2),
    STOCK INT NOT NULL,
    ESTADO TINYINT NOT NULL,
    IMAGEN VARCHAR(255),
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CODCATEGORIA)
);

-- =========================
-- VARIANTES
-- =========================
CREATE TABLE PRODUCTO_VARIANTE (
    IDVARIANTE INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO_ID INT NOT NULL,
    TALLA VARCHAR(50),
    COLOR VARCHAR(50),
    PRECIO DECIMAL(10,2),
    STOCK INT,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID)
);

-- =========================
-- CARRITO
-- =========================
CREATE TABLE CARRITO (
    IDCARRITO INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE CARRITO_DETALLE (
    IDCARRITO_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    CARRITO_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (CARRITO_ID) REFERENCES CARRITO(IDCARRITO),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES PRODUCTO_VARIANTE(IDVARIANTE)
);

-- =========================
-- MÉTODOS DE PAGO
-- =========================
CREATE TABLE METODO_PAGO (
    IDMETODO_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL
);

-- =========================
-- PEDIDOS
-- =========================
CREATE TABLE PEDIDO (
    IDPEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    FECHAENTREGA DATETIME,
    DIRECCION VARCHAR(255) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE PEDIDO_DETALLE (
    IDPEDIDO_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(IDPEDIDO),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES PRODUCTO_VARIANTE(IDVARIANTE)
);

-- =========================
-- VENTAS
-- =========================
CREATE TABLE VENTA (
    IDVENTA INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    PEDIDO_ID INT NOT NULL,
    CODIGO VARCHAR(255) NOT NULL,
    PRECIO_TOTAL DECIMAL(10,2) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(IDPEDIDO),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE VENTA_DETALLE (
    IDVENTA_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES VENTA(IDVENTA),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES PRODUCTO_VARIANTE(IDVARIANTE)
);

-- =========================
-- PAGOS
-- =========================
CREATE TABLE PAGO (
    IDPAGO INT AUTO_INCREMENT PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    METODO_PAGO_ID INT NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA DATETIME NOT NULL,
    ESTADO TINYINT NOT NULL,
    TRANSACCION_EXTERNA VARCHAR(255),
    FOREIGN KEY (VENTA_ID) REFERENCES VENTA(IDVENTA),
    FOREIGN KEY (METODO_PAGO_ID) REFERENCES METODO_PAGO(IDMETODO_PAGO)
);

-- =========================
-- NOTIFICACIONES
-- =========================
CREATE TABLE NOTIFICACION (
    IDNOTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    MENSAJE TEXT NOT NULL,
    TIPO VARCHAR(50),
    LEIDO TINYINT DEFAULT 0,
    CREATEDAT DATETIME NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

-- =========================
-- ENVÍOS
-- =========================
CREATE TABLE ENVIO (
    IDENVIO INT AUTO_INCREMENT PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    FECHA_ENVIO DATETIME,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES VENTA(IDVENTA)
);

-- =========================
-- RESEÑAS
-- =========================
CREATE TABLE RESENA (
    IDRESENA INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO_ID INT NOT NULL,
    CLIENTE_ID INT NOT NULL,
    CALIFICACION INT NOT NULL,
    COMENTARIO TEXT,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

-- =========================
-- DESCUENTOS
-- =========================
CREATE TABLE DESCUENTO (
    IDDESCUENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    PORCENTAJE DECIMAL(5,2) NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL
);

CREATE TABLE PRODUCTO_DESCUENTO (
    IDPRODUCTO_DESCUENTO INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO_ID INT NOT NULL,
    DESCUENTO_ID INT NOT NULL,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID),
    FOREIGN KEY (DESCUENTO_ID) REFERENCES DESCUENTO(IDDESCUENTO)
);

-- =========================
-- WISHLIST
-- =========================
CREATE TABLE WISHLIST (
    IDWISHLIST INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    NOMBRE VARCHAR(255),
    CREATEDAT DATETIME NOT NULL,
    UPDATEDAT DATETIME NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE WISHLIST_PRODUCTO (
    IDWISHLIST_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    WISHLIST_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    FOREIGN KEY (WISHLIST_ID) REFERENCES WISHLIST(IDWISHLIST),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES PRODUCTO_VARIANTE(IDVARIANTE)
);

-- =========================
-- DATOS INICIALES
-- =========================

-- ROLES
INSERT INTO ROL (NOMBRE) VALUES ('ADMIN'), ('CLIENTE');

-- PERMISOS
INSERT INTO PERMISO (NOMBRE) VALUES
('CREAR_PRODUCTO'),
('EDITAR_PRODUCTO'),
('ELIMINAR_PRODUCTO'),
('VER_PRODUCTO'),
('GESTIONAR_PEDIDOS'),
('VER_REPORTES'),
('COMPRAR'),
('VER_CARRITO');

-- ADMIN (todos los permisos)
INSERT INTO ROL_PERMISO (ROL_ID, PERMISO_ID)
SELECT 1, IDPERMISO FROM PERMISO;

-- CLIENTE (limitado)
INSERT INTO ROL_PERMISO (ROL_ID, PERMISO_ID) VALUES
(2, 4),
(2, 7),
(2, 8);  